include $(GOROOT)/src/Make.inc

TARG=code.google.com/p/draw2d/raster
GOFILES=\
	line.go\
	polygon.go\
	coverage_table.go\
	fillerAA.go\
	filler.go\
	fixed_point.go
	

include $(GOROOT)/src/Make.pkg
